version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "7777:80"
    volumes:
      - /home/dhhan/infra/conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - /home/dhhan/infra/client:/usr/share/nginx/html
    restart: unless-stopped
