version: '3.8'

services:
  health-app:
    image: eclipse-temurin:21-jdk
    container_name: wearable-server
    
    # 8080 포트를 호스트의 8080 포트로 매핑합니다.
    # Java 애플리케이션이 이 포트에서 실행된다고 가정합니다.
    ports:
      - "8081:8081"
      
    # Java 애플리케이션의 JAR 파일을 컨테이너 내부로 마운트합니다.
    volumes:
      # 로컬 경로의 JAR 파일을 컨테이너의 실행 경로로 마운트
      # 경로를 사용자 환경에 맞게 변경해주세요.
      - /home/dhhan/infra/v-wearable/healthServer.jar:/app/app.jar:Z
      
    # 애플리케이션 실행 명령어
    command: java -jar /app/app.jar

  # --- Nginx 웹 서버 서비스 ---
  health-nginx:
    # 공식 Nginx 이미지를 사용합니다.
    image: nginx:latest
    container_name: nginx-server
    
    # 80 포트를 호스트의 80 포트로 매핑합니다.
    ports:
      - "8011:80"
      
    # Java 애플리케이션으로의 리버스 프록시 및 정적 콘텐츠를 위해 볼륨 마운트
    volumes:
      # 1. Nginx 설정 파일 마운트 (필수)
      # 로컬 경로의 nginx.conf 파일을 컨테이너의 기본 설정 파일로 마운트
      - /home/dhhan/infra/v-wearable/nginx.conf:/etc/nginx/nginx.conf:Z
      
      # 2. 정적 콘텐츠 폴더 마운트 (선택 사항)
      # 로컬 경로의 HTML/CSS/JS 파일들을 Nginx의 기본 웹 루트로 마운트
      - /home/dhhan/infra/v-wearable/client:/etc/nginx/html:Z
      
    # Java 앱보다 먼저 시작되도록 종속성 설정 (네트워킹)
    depends_on:
      - health-app

# --- 볼륨 정의 (필요에 따라) ---
# 이 구성에서는 로컬 디렉토리 마운트만 사용했기 때문에 명시적인 named volume 정의는 생략했습니다.
# 만약 named volume이 필요하다면 아래 섹션을 추가하세요.
# volumes:
#   nginx_logs:
#   java_data:
